- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    ignore_errors: yes
    
  - name: say Hello
    ansible.builtin.debug:
      msg: "Hello"


