#1. Create 3 ec2 servers
#2. Update route53 records

#solution: Authenticate AWS

- name: create ec2 and r53 records
  hosts: localhost
  vars:
     zone: swamy.fun
     instances:
     - db
     - backend
     - frontend
  tasks:
    - name: create ec2 instances
      amazon.aws.ec2_instance: 
        instance_type: t2.micro
        name: "{{ item }}"
        security_group: allow-everything
        image_id: ami-09c813fb71547fc4f
        tags:
           Name: "{{ item }}"
      loop:
      - "{{ instances }}"
      register: ec2_instances_info

    - name: print output
      ansible.builtin.debug:
         msg: " Output: {{ ec2_instances_info }} "
     
    - name: create route53 records
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item }}.{{ zone }}"
        type: A
        value: "{{ item.private_ip_address }}"
        overwrite: true
        ttl: 1
      loop: "{{ result.instances }}"
      





