#1. Create 3 ec2 servers
#2. Update route53 records

#solution: Authenticate AWS

- name: create ec2 and r53 records
  hosts: localhost
  vars:
     zone: swamy.fun
  tasks:
    - name: create ec2 instances
      amazon.aws.ec2_instance: 
        instance_type: t2.micro
        name: "{{ item }}"
        security_group: allow-everything
        image_id: ami-09c813fb71547fc4f
        tags:
           Name: "{{ item }}"
      loop:
      - db
      - backend
      - frontend
      register: ec2_instances_info

    - name: create route53 records
      amazon.aws.route53:
        record: 




